### ISSUE TITLE
 Class 'voku\Cart\Cart' not found

### ISSUE THREAD

**Issue by mrsnax** [voku/cart#1]
I got error when using this class ? Whats wrong ?

 Class 'voku\Cart\Cart' not found

Any Suggestion ?

**Comment by voku** [comment]
autoload.php is loaded?

**Comment by mrsnax** [comment]
All loaded correctly

**Comment by voku** [comment]
thx for the bug report, fixed via https://github.com/voku/cart/commit/8fb76e909679815b80b3fc6a733739db9e5105db

(tag 1.0.2)
